<?php
DEFINE('DB_HOST','localhost');
DEFINE('DB_USER','maxigang1617');
DEFINE('DB_PASSWD','2kqPae');
DEFINE('DB_DATABASE','maxigang1617');
/*
DEFINE('DB_HOST','void.ugr.es');
DEFINE('DB_USER','jacquesmeyns1617');
DEFINE('DB_PASSWD','bvuEIu');
DEFINE('DB_DATABASE','jacquesmeyns1617');
*/
?>
